name: CI
run-name: ${{ github.event.pull_request.head.ref }}
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  # The "format" job checks that the style guide is followed correctly.
  format:
    runs-on: ubuntu-latest
    steps:
      # Use actions/checkout@v4 with fetch-depth: 0 to get a deep checkout for the formatter.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # Checks the code format with gradle
      - name: Check formatting
        run: ./gradlew spotlessCheck

   # The "build" job checks that the robot code builds correctly and that any unit tests pass.
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # Use actions/checkout@v4 with fetch-depth: 0 to get a deep checkout for the formatter.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # Runs a single command using the runners shell
      - name: Compile and run tests on robot code
        run: ./gradlew build

      # Upload test artifacts
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: ${{ github.workspace }}/build/test-results/frcUserProgramTest
